global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "engine"
    static_configs:
      - targets: ["host.docker.internal:9101"]

  - job_name: "ws-server"
    static_configs:
      - targets: ["host.docker.internal:9102"]

  - job_name: "nextjs"
    metrics_path: "/api/v1/metrics"
    static_configs:
      - targets: ["host.docker.internal:3000"]
