name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Turbo Prune Web
        run: npx turbo prune web --docker
      - name: Turbo Prune Engine
        run: npx turbo prune engine --docker
      - name: Turbo Prune WS-Server
        run: npx turbo prune ws-server --docker

      - name: Build & Push Web
        run: |
          docker build -f docker/Dockerfile.web -t ${{ secrets.DOCKER_USERNAME }}//crypto-web:latest ./out/full
          docker push ${{ secrets.DOCKER_USERNAME }}//crypto-web:$latest
      - name: Build & Push Engine
        run: |
          docker build -f docker/Dockerfile.engine -t ${{ secrets.DOCKER_USERNAME }}//crypto-engine:latest ./out/full
          docker push ${{ secrets.DOCKER_USERNAME }}//crypto-engine:$latest
      - name: Build & Push WS-Server
        run: |
          docker build -f docker/Dockerfile.ws-server -t ${{ secrets.DOCKER_USERNAME }}//crypto-ws:latest ./out/full
          docker push ${{ secrets.DOCKER_USERNAME }}//crypto-ws:$latest

      - name: Prepare EC2 directory
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            mkdir -p ~/application

      - name: Copy docker-compose.prod.yml to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.prod.yml"
          target: "~/application"

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ vars.EC2_HOST }}
          username: ${{ vars.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/application
            rm -f .env
            echo "DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@postgres:5432/${{ secrets.POSTGRES_DB }}" >> .env
            echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
            echo "SALT_ROUNDS=${{ secrets.SALT_ROUNDS }}" >> .env
            echo "REDIS_CHANNEL_ORDERBOOK_PREFIX=${{ vars.REDIS_CHANNEL_ORDERBOOK_PREFIX }}" >> .env
            echo "REDIS_CHANNEL_TRADE_PREFIX=${{ vars.REDIS_CHANNEL_TRADE_PREFIX }}" >> .env
            echo "NEXT_PUBLIC_WS_URL=wss://${{ vars.EC2_HOST }}:8080" >> .env
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d
